[package]
name = "cardwire-dbus"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Traits for cardwire's dbus"


[dependencies]
zbus.workspace = true
serde.workspace = true
cardwire-core = { path = "../cardwire-core" }
