#![no_std]
#![no_main]

use aya_ebpf::{
    helpers::{bpf_get_current_comm, bpf_get_current_pid_tgid}, macros::lsm, programs::LsmContext
};
use aya_log_ebpf::{error, info, warn};

use crate::{
    helpers::{is_cardwired, is_hybrid, is_inode_blocked}, vmlinux::{dentry, file, inode}
};

#[allow(
    clippy::all,
    dead_code,
    improper_ctypes_definitions,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unnecessary_transmutes,
    unsafe_op_in_unsafe_fn,
)]
#[rustfmt::skip]
mod vmlinux;

mod helpers;

mod maps;

struct ReturnCode {}
impl ReturnCode {
    // Succes means we didn't block the process
    const SUCCESS: Result<i32, i32> = Ok(0);
    // ENOENT means we blocked the process, it can't see the file
    const ENOENT: Result<i32, i32> = Ok(-2);
}

// Used of CW_DAEMON_PID array
const DAEMON_INDEX: u32 = 0;

struct CardwiredSetting {}
impl CardwiredSetting {
    const EXP_NVIDIA: u8 = 0;
}
/*
    Modes
*/
const MODE_INDEX: u32 = 0;
const INTEGRATED: u8 = 0;
const HYBRID: u8 = 1;
const MANUAL: u8 = 2;
const SMART: u8 = 3;

// About verifications:
// All hooks must call the verifications functions before reading any ptr and doing actions
// This prevent slowing down the kernel without justification
// Eg. If the system is on hybrid, we do not need to check if the GPU should be hidden, just skip
// the event

// List of current verifications:
// is_cardwired() -> verify if the event was generated by the daemon, if true skip
// is_comm_whitelisted() -> verify if the event was generated by a whitelisted comm, if true skip
// is_hybrid() -> verify if the system is in hybrid, if true skip
// if is_smart() -> verify if the system is in smart, only for sched_process_exec and
//  sched_process_exit, if false skip in these hooks

#[lsm(hook = "file_open")]
pub fn lsm_file_open(ctx: LsmContext) -> i32 {
    match unsafe { try_file_open(ctx) } {
        Ok(ret) => ret,
        Err(ret) => ret,
    }
}

unsafe fn try_file_open(ctx: LsmContext) -> Result<i32, i32> {
    // If it's the daemon, we must exit
    match is_cardwired() {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(&ctx, "EBPF is_cardwired() produced an error, exiting");
            return ReturnCode::SUCCESS;
        }
    }

    // If the mode is hybrid, we must exit
    match unsafe { is_hybrid() } {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(&ctx, "EBPF is_hybrid() produced an error, exiting");
            return ReturnCode::SUCCESS;
        }
    }

    let d: *mut dentry = unsafe {
        // arg.0 of file_open is a file
        let file_ptr: *const file = ctx.arg(0);
        (*file_ptr).__bindgen_anon_1.f_path.dentry
    };

    // if no dentry, exit
    if d.is_null() {
        return ReturnCode::SUCCESS;
    }

    // Get a mutable ptr to the inode
    let inode_ptr: *mut inode = unsafe { (*d).d_inode };

    if inode_ptr.is_null() {
        return ReturnCode::SUCCESS;
    }

    unsafe { is_inode_blocked(&ctx, inode_ptr) }
}

#[cfg(not(test))]
#[panic_handler] // (3)
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}
