#![no_std]
#![no_main]

use aya_ebpf::{
    helpers::{bpf_get_current_pid_tgid, bpf_probe_read_user, bpf_probe_write_user}, macros::{lsm, tracepoint}, programs::{LsmContext, TracePointContext}
};
use aya_log_ebpf::{error, warn};

use crate::{
    helpers::{is_cardwired, is_hybrid, is_inode_blocked, is_smart}, maps::{CW_CLOSE_EVENTS, CW_DIRENT, CW_EXEC_EVENTS, CloseEvent, ExecEvent}, vmlinux::{dentry, file, inode, linux_dirent64, path}
};

#[allow(
    clippy::all,
    dead_code,
    improper_ctypes_definitions,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unnecessary_transmutes,
    unsafe_op_in_unsafe_fn,
)]
#[rustfmt::skip]
mod vmlinux;

mod helpers;

mod maps;

struct ReturnCode {}
impl ReturnCode {
    // Succes means we didn't block the process
    const SUCCESS: Result<i32, i32> = Ok(0);
    // ENOENT means we blocked the process, it can't see the file
    const ENOENT: Result<i32, i32> = Ok(-2);
}

// Used of CW_DAEMON_PID array
const DAEMON_INDEX: u32 = 0;

struct CardwiredSetting {}
impl CardwiredSetting {
    const EXP_NVIDIA: u8 = 0;
}
/*
    Modes
*/
const MODE_INDEX: u32 = 0;
const INTEGRATED: u8 = 0;
const HYBRID: u8 = 1;
const MANUAL: u8 = 2;
const SMART: u8 = 3;

// About verifications:
// All hooks must call the verifications functions before reading any ptr and doing actions
// This prevent slowing down the kernel without justification
// Eg. If the system is on hybrid, we do not need to check if the GPU should be hidden, just skip
// the event

// List of current verifications:
// is_cardwired() -> verify if the event was generated by the daemon, if true skip
// is_comm_whitelisted() -> verify if the event was generated by a whitelisted comm, if true skip
// is_hybrid() -> verify if the system is in hybrid, if true skip
// if is_smart() -> verify if the system is in smart, only for sched_process_exec and
//  sched_process_exit, if false skip in these hooks

#[lsm(hook = "file_open")]
pub fn file_open(ctx: LsmContext) -> i32 {
    match unsafe { try_file_open(ctx) } {
        Ok(ret) => ret,
        Err(ret) => ret,
    }
}

unsafe fn try_file_open(ctx: LsmContext) -> Result<i32, i32> {
    // If it's the daemon, we must exit
    match is_cardwired() {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(
                &ctx,
                "EBPF is_cardwired() produced an error in file_open, skipping"
            );
            return ReturnCode::SUCCESS;
        }
    }

    // If the mode is hybrid, we must exit
    match unsafe { is_hybrid() } {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(
                &ctx,
                "EBPF is_hybrid() produced an error in file_open, skipping"
            );
            return ReturnCode::SUCCESS;
        }
    }

    let d: *mut dentry = unsafe {
        // arg.0 of file_open is a file
        let file_ptr: *const file = ctx.arg(0);
        (*file_ptr).__bindgen_anon_1.f_path.dentry
    };

    // if no dentry, exit
    if d.is_null() {
        return ReturnCode::SUCCESS;
    }

    // Get a mutable ptr to the inode
    let inode_ptr: *mut inode = unsafe { (*d).d_inode };

    if inode_ptr.is_null() {
        return ReturnCode::SUCCESS;
    }
    let inode: u64 = unsafe { (*inode_ptr).i_ino };

    match unsafe { is_inode_blocked(inode) } {
        true => ReturnCode::ENOENT,
        false => ReturnCode::SUCCESS,
    }
}

#[lsm(hook = "inode_permission")]
pub fn inode_permission(ctx: LsmContext) -> i32 {
    match unsafe { try_inode_permission(ctx) } {
        Ok(ret) => ret,
        Err(ret) => ret,
    }
}

unsafe fn try_inode_permission(ctx: LsmContext) -> Result<i32, i32> {
    // If it's the daemon, we must exit
    match is_cardwired() {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(
                &ctx,
                "EBPF is_cardwired() produced an error in inode_permission, skipping"
            );
            return ReturnCode::SUCCESS;
        }
    }

    // If the mode is hybrid, we must exit
    match unsafe { is_hybrid() } {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(
                &ctx,
                "EBPF is_hybrid() produced an error in inode_permission, skipping"
            );
            return ReturnCode::SUCCESS;
        }
    }

    // Get a mutable ptr to the inode, in inode_permission it's the first argument
    let inode_ptr: *mut inode = ctx.arg(0);

    if inode_ptr.is_null() {
        return ReturnCode::SUCCESS;
    }
    let inode: u64 = unsafe { (*inode_ptr).i_ino };

    match unsafe { is_inode_blocked(inode) } {
        true => ReturnCode::ENOENT,
        false => ReturnCode::SUCCESS,
    }
}

#[lsm(hook = "inode_getattr")]
pub fn inode_getattr(ctx: LsmContext) -> i32 {
    match unsafe { try_inode_getattr(ctx) } {
        Ok(ret) => ret,
        Err(ret) => ret,
    }
}

unsafe fn try_inode_getattr(ctx: LsmContext) -> Result<i32, i32> {
    // If it's the daemon, we must exit
    match is_cardwired() {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(
                &ctx,
                "EBPF is_cardwired() produced an error in inode_getattr, skipping"
            );
            return ReturnCode::SUCCESS;
        }
    }

    // If the mode is hybrid, we must exit
    match unsafe { is_hybrid() } {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(
                &ctx,
                "EBPF is_hybrid() produced an error in inode_getattr, skipping"
            );
            return ReturnCode::SUCCESS;
        }
    }

    let path_ptr: *const path = ctx.arg(0);

    let dentry_ptr: *mut dentry = unsafe { (*path_ptr).dentry };

    if dentry_ptr.is_null() {
        return ReturnCode::SUCCESS;
    }

    // Get a mutable ptr to the inode, in inode_permission it's the first argument
    let inode_ptr: *mut inode = unsafe { (*dentry_ptr).d_inode };

    if inode_ptr.is_null() {
        return ReturnCode::SUCCESS;
    }
    let inode: u64 = unsafe { (*inode_ptr).i_ino };

    match unsafe { is_inode_blocked(inode) } {
        true => ReturnCode::ENOENT,
        false => ReturnCode::SUCCESS,
    }
}

#[tracepoint]
pub fn tracepoint_enter_getdents64(ctx: TracePointContext) -> u32 {
    match unsafe { try_tracepoint_enter_getdents64(ctx) } {
        Ok(ret) => ret as u32,
        Err(ret) => ret as u32,
    }
}

unsafe fn try_tracepoint_enter_getdents64(ctx: TracePointContext) -> Result<i32, i32> {
    // If it's the daemon, we must exit
    match is_cardwired() {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(
                &ctx,
                "EBPF is_cardwired() produced an error in tracepoint_enter_getdents64, skipping"
            );
            return ReturnCode::SUCCESS;
        }
    }

    // If the mode is hybrid, we must exit
    match unsafe { is_hybrid() } {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(
                &ctx,
                "EBPF is_hybrid() produced an error in tracepoint_enter_getdents64, skipping"
            );
            return ReturnCode::SUCCESS;
        }
    }

    const DIRP_OFFSET: usize = 24;

    let pid = (bpf_get_current_pid_tgid() >> 32) as u32;

    let dirp_ptr: u64 = unsafe { ctx.read_at(DIRP_OFFSET)? };

    CW_DIRENT.insert(&pid, &dirp_ptr, 0)?;

    ReturnCode::SUCCESS
}

#[tracepoint]
pub fn tracepoint_exit_getdents64(ctx: TracePointContext) -> u32 {
    match unsafe { try_tracepoint_exit_getdents64(ctx) } {
        Ok(ret) => ret as u32,
        Err(ret) => ret as u32,
    }
}

unsafe fn try_tracepoint_exit_getdents64(ctx: TracePointContext) -> Result<i32, i32> {
    // If it's the daemon, we must exit
    match is_cardwired() {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(
                &ctx,
                "EBPF is_cardwired() produced an error in tracepoint_exit_getdents64, skipping"
            );
            return ReturnCode::SUCCESS;
        }
    }

    // If the mode is hybrid, we must exit
    match unsafe { is_hybrid() } {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(
                &ctx,
                "EBPF is_hybrid() produced an error in tracepoint_exit_getdents64, skipping"
            );
            return ReturnCode::SUCCESS;
        }
    }

    let pid = (bpf_get_current_pid_tgid() >> 32) as u32;
    let dirent_ptr = match unsafe { CW_DIRENT.get(&pid) } {
        Some(ptr) => *ptr as *const linux_dirent64,
        None => return ReturnCode::SUCCESS,
    };

    let retval = match unsafe { ctx.read_at::<i64>(16) } {
        Ok(ret) => ret as u64,
        Err(_) => return ReturnCode::SUCCESS,
    };

    if retval == 0 || retval > 32768 {
        return ReturnCode::SUCCESS;
    }

    // Buffer end = base + bytes written
    let base = dirent_ptr as u64;
    let end = base.wrapping_add(retval);

    let mut dirent_ptr = dirent_ptr;
    let mut prev_ptr: u64 = 0;
    let mut prev_reclen: u16 = 0;
    for _ in 0..512 {
        // Check before reading
        if (dirent_ptr as u64).wrapping_add(core::mem::size_of::<linux_dirent64>() as u64) > end {
            break;
        }

        let dirent = match unsafe { bpf_probe_read_user(dirent_ptr) } {
            Ok(dirent) => dirent,
            Err(_) => break,
        };

        let reclen = dirent.d_reclen;

        // Malformed
        if reclen == 0 || reclen > 512 {
            break;
        }

        let blocked = unsafe { is_inode_blocked(dirent.d_ino) };
        if blocked {
            // We can't hide the first entry
            if prev_ptr != 0 {
                let new_reclen = prev_reclen.wrapping_add(reclen);

                let reclen_ptr = (prev_ptr.wrapping_add(16)) as *mut u16;
                match unsafe { bpf_probe_write_user(reclen_ptr, &new_reclen) } {
                    Ok(_) => {}
                    Err(err) => {
                        error!(&ctx, "failed to write new reclen {}", err);
                        break;
                    }
                };

                prev_reclen = new_reclen;
            }
        } else {
            prev_ptr = dirent_ptr as u64;
            prev_reclen = reclen;
        }

        dirent_ptr = (dirent_ptr as u64).wrapping_add(reclen as u64) as *const linux_dirent64;
    }

    ReturnCode::SUCCESS
}

#[tracepoint]
pub fn tracepoint_sched_process_exec(ctx: TracePointContext) -> u32 {
    match unsafe { try_tracepoint_sched_process_exec(ctx) } {
        Ok(ret) => ret as u32,
        Err(ret) => ret as u32,
    }
}

unsafe fn try_tracepoint_sched_process_exec(ctx: TracePointContext) -> Result<i32, i32> {
    // If it's the daemon, we must exit
    match is_cardwired() {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(
                &ctx,
                "EBPF is_cardwired() produced an error in tracepoint_sched_process_exec, skipping"
            );
            return ReturnCode::SUCCESS;
        }
    }

    // Only proceed if we are in smart mode, events are not used when not in smart mode and it would
    // slow down the system for no reason
    if let Some(res) = unsafe { is_smart() }
        && res
    {
        // Reserve byte in the ring buf for the event, return if fail
        let mut ring_buf = match CW_EXEC_EVENTS.reserve(0) {
            Some(ring_buf) => ring_buf,
            // Reservation fail, warn and leave
            None => {
                warn!(&ctx, "failed to reserve bytes for ring_buf: CW_EXEC_EVENTS");
                return ReturnCode::SUCCESS;
            }
        };
        let pid = (bpf_get_current_pid_tgid() >> 32) as u32;

        // We just send the event to userspace
        let event: ExecEvent = ExecEvent { pid };

        // Now submit the event
        ring_buf.write(event);
        ring_buf.submit(0);
    }

    ReturnCode::SUCCESS
}

#[tracepoint]
pub fn tracepoint_sched_process_exit(ctx: TracePointContext) -> u32 {
    match unsafe { try_tracepoint_sched_process_exit(ctx) } {
        Ok(ret) => ret as u32,
        Err(ret) => ret as u32,
    }
}

unsafe fn try_tracepoint_sched_process_exit(ctx: TracePointContext) -> Result<i32, i32> {
    // If it's the daemon, we must exit
    match is_cardwired() {
        Some(res) => {
            if res {
                return ReturnCode::SUCCESS;
            }
        }
        None => {
            // This error happen if either the array is not available or the index 0 of the array is
            // empty
            error!(
                &ctx,
                "EBPF is_cardwired() produced an error in tracepoint_sched_process_exec, skipping"
            );
            return ReturnCode::SUCCESS;
        }
    }

    // Only proceed if we are in smart mode, events are not used when not in smart mode and it would
    // slow down the system for no reason
    if let Some(res) = unsafe { is_smart() }
        && res
    {
        let pid_tgid: u64 = bpf_get_current_pid_tgid();
        let tgid = pid_tgid as u32;
        let pid = (pid_tgid >> 32) as u32;

        // Only send close event if the main thread is exiting
        if pid != tgid {
            return ReturnCode::SUCCESS;
        }

        let event: CloseEvent = CloseEvent { pid };

        let mut ring_buf = match CW_CLOSE_EVENTS.reserve(0) {
            Some(ring_buf) => ring_buf,
            // Reservation fail, warn and leave
            None => {
                warn!(
                    &ctx,
                    "failed to reserve bytes for ring_buf: CW_CLOSE_EVENTS"
                );
                return ReturnCode::SUCCESS;
            }
        };

        ring_buf.write(event);
        ring_buf.submit(0);
    }

    ReturnCode::SUCCESS
}

#[cfg(not(test))]
#[panic_handler] // (3)
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}
