[package]
name = "cardwire-smart"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Cardwire task used to process on-the-fly GPU whitelisting"

[dependencies]
cardwire-core = { path = "../cardwire-core" }
cardwire-ebpf-userspace = { path = "../cardwire-ebpf-userspace" }
cardwire-analyzer = { path = "../cardwire-analyzer" }
tokio.workspace = true
aya.workspace = true
thiserror.workspace = true
log.workspace = true