[package]
name = "cardwire-tray"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Status notifier applet for Cardwire GPU management"

[features]
default = ["applet"]
applet = [
    "dep:env_logger",
    "dep:ksni",
    "dep:log",
    "dep:notify-rust",
    "dep:tokio",
    "dep:tokio-stream",
    "dep:zbus",
]

[dependencies]
serde.workspace = true
toml.workspace = true
xdg.workspace = true
env_logger = { workspace = true, optional = true }
ksni = { workspace = true, optional = true }
log = { workspace = true, optional = true }
notify-rust = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
tokio-stream = { workspace = true, optional = true }
zbus = { workspace = true, optional = true }
