name: Integration Tests in a Nix VM
on:
  pull_request:
    types: [opened, labeled]
    branches:
      - main
    paths:
      - 'crates/**'
      - 'workflows/**'
      - 'nix/**'
jobs:
  run-test:
    if: ${{ github.event.label.name == 'run-vm-test' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Run Integration Tests
        run: nix build -L .#checks.x86_64-linux.vm-test
