name: ci/cd

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      run_nix_vm: ${{ steps.files.outputs.run_nix_vm }}
      run_c_checks: ${{ steps.files.outputs.run_c_checks }}
      run_rust_checks: ${{ steps.files.outputs.run_rust_checks }}
    steps:
      - name: Determine changed files
        id: files
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const files = (await github.paginate(github.rest.pulls.listFiles, {
              ...context.repo,
              pull_number: context.payload.pull_request.number,
              per_page: 100,
            })).map(file => file.filename)

            const needsVMTest = files.some(file => 
              file.endsWith('.rs') || 
              file.endsWith('.c') || 
              file.includes('.nix') ||
              file.includes('flake.lock') ||
              file.includes('Cargo.toml') || 
              file.includes('Cargo.lock')
            );

            const needsCFormatCheck = files.some(file => 
              file.endsWith('.c')
            );

            const needsRustQuality = files.some(file => 
              file.endsWith('.rs')
            );

            if (needsVMTest) {
              core.setOutput('run_nix_vm', 'true');
            }
            if (needsCFormatCheck) {
              core.setOutput('run_c_checks', 'true');
            }
            if (needsRustQuality) {
              core.setOutput('run_rust_checks', 'true');
            }

  setup-nix:
    name: Setup Nix Cache
    runs-on: ubuntu-latest
    needs: [prepare]
    if: needs.prepare.outputs.run_nix_vm == 'true' || needs.prepare.outputs.run_c_checks == 'true' || needs.prepare.outputs.run_rust_checks == 'true'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: determinateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: determinateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - run: nix develop --command true

  rust-lint:
    name: Rust Lint
    runs-on: ubuntu-latest
    needs: [prepare, setup-nix]
    if: needs.prepare.outputs.run_rust_checks == 'true'
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: determinateSystems/nix-installer-action@main
    - uses: determinateSystems/magic-nix-cache-action@main
    - run: nix develop --command cargo clippy --locked --all-targets --all-features -- -D warnings


  rust-format:
    name: Rust Format
    runs-on: ubuntu-latest
    needs: [prepare, setup-nix]
    if: needs.prepare.outputs.run_rust_checks == 'true'
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: determinateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
    - uses: determinateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
    - run: nix develop --command cargo fmt -- --check

  c-format:
    name: C Format
    runs-on: ubuntu-latest
    needs: [prepare, setup-nix]
    if: needs.prepare.outputs.run_c_checks == 'true'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: determinateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: determinateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - run: nix develop --command clang-format --dry-run --Werror -i ./crates/cardwire-ebpf/src/bpf.c

  vm-test:
    runs-on: ubuntu-latest
    needs: [prepare, setup-nix, rust-lint, rust-format, c-format]
    if: ${{ !failure() && !cancelled() && needs.prepare.outputs.run_nix_vm == 'true' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: determinateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: determinateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - run: nix build .#vm-test