name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build-and-upload:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libbpf-dev libudev-dev pkg-config

      - name: Install gcc-multilib
        if: matrix.os == 'ubuntu-24.04'
        run: sudo apt-get install -y gcc-multilib

      - name: Fix missing asm/types.h on arm64
        if: matrix.os == 'ubuntu-24.04-arm'
        run: |
          sudo ln -s /usr/include/aarch64-linux-gnu/asm /usr/include/asm


      - uses: dtolnay/rust-toolchain@1.95.0
      - name: Build cardwire
        run: |
          cargo install cargo-deb
          cargo build --release --locked
          cargo deb --no-build

      - name: Find deb filename
        id: deb
        run: |
          DEB_FILE=$(basename target/debian/*.deb)
          echo "name=${DEB_FILE}" >> "$GITHUB_OUTPUT"

      - name: Upload deb
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.deb.outputs.name }}
          path: "target/debian/*.deb"
          if-no-files-found: error